### ISSUE TITLE
group重复时没有自动合并

### ISSUE THREAD

**Issue by fgfg163** [LeoChen98/ClashYamlParser#11]
![Image](https://github.com/user-attachments/assets/30c1963e-63bc-459d-8c00-427023a20726)

当插入的groups是重复节点时，官方会合并重复的group但是这里却生成了两个节点

```
parsers:
  - reg: ^https://.*
    yaml:
      append-proxies:
        - name: sg server
          type: socks5
          server: 127.0.0.1
          skip-cert-verify: true
          port: 7891
          udp: true
      prepend-proxy-groups:
        - name: "🔰 选择节点"
          type: select
          proxies:
          - "sg server"
```
